FROM docker.io/library/alpine:3.23.3

RUN adduser -S -u 99 -D -G users mirroruser

RUN apk add --no-cache rsync bash curl openssl cronie \
  && mkdir -p /srv/mirror \
  && chown -R mirroruser:users /srv/mirror

COPY rsync-archlinux.sh /usr/local/bin/rsync-archlinux
COPY --chmod=0600 crontab-mirroruser /etc/crontabs/mirroruser

RUN chmod +x /usr/local/bin/rsync-archlinux

ENTRYPOINT ["crond", "-n"]
