FROM docker.io/library/alpine:3.23.3

RUN adduser -S -u 99 -D -G users mirroruser \
  && mkdir -p /srv/mirror \
  && mkdir -p /config/logs \
  && chown -R mirroruser:users /srv/mirror \
  && chown -R mirroruser:users /config/logs

RUN apk add --no-cache nginx

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
