FROM docker.io/library/alpine:3.23.3

RUN addgroup -S -g 100 mirroruser \
  && adduser -S -u 99 -D -G mirroruser mirroruser \
  && mkdir -p /srv/mirror \
  && mkdir -p /config/logs \
  && chown -R mirroruser:mirroruser /srv/mirror \
  && chown -R mirroruser:mirroruser /config/logs

RUN apk add --no-cache nginx

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
